package projetstage;

import java.util.Arrays;
import java.util.List;

public class Config {

   public static final int O = 0;
   public static final int I = 1;
   public static final int II = 2;
   public static final int III = 3;
   public static final int IV = 4;
   public static final int V = 5;
   public static final int VI = 6;
   public static final int VII = 7;
   public static final int VIII = 8;
   public static final int IX = 9;
   public static final int X = 10;
   public static final int XI = 11;
   public static final int XII = 12;
   public static final int XIII = 13;
   public static final int XIV = 14;
   public static final int XV = 15;
   public static final int XVI = 16;
   public static final int XVII = 17;
   public static final int XVIII = 18;
   public static final int XIX = 19;
   public static final int XX = 20;
   public static final int XXI = 21;
   public static final int XXII = 22;
   public static final int XXIII = 23;
   public static final int XXIV = 24;
   public static final int XXV = 25;
   public static final int XXVI = 26;
   public static final int XXVII = 27;
   public static final int XXVIII = 28;
   public static final int XXIX = 29;
   public static final int CXXVI = 126;
   public static final int CXXVIII = 128;
   public static final int CXXIX = 129;
   public static final int CXXX = 130;
   public static final int CXXXI = 131;
   public static final int CCXLVIII = 248;
   public static final int CCLXXXII = 282;
   public static final int CCLXXXIII = 283;
   public static final int CCCXXXVIII = 338;
   public static final int CCCX = 310;
   public static final int CCCXXXIX = 339;
   public static final int DCII = 602;
   public static final int DCIII = 603;
   public static final int DCXXIX = 629;
   public static final int DCXXX = 630;
   public static final int CMXVIII = 918;
   public static final int CMLIV = 954;
   public static final int CMLV = 955;
   public static final int MCCCVI = 1306;
   public static final int MCCCVII = 1307;
   public static final int MCCCVIII = 1308;
   public static final int MCCCLIII = 1353;
   public static final int MCDIIX = 1408;
   public static final int MCDIX = 1409;
   public static final int MCDX = 1410;
   public static final int MCDXI = 1411;

   public static final String SPACE = " ";
   public static final String NONAPPLICABLE = "Non-Applicable";
   public static final String AUTRE = "Autre";
   public static final String COMMENTAIRE = "Commentaire";
   public static final String SPORT = "Sport et science du mouvement";
   public static final String SANTE = "Santé";
   public static final String AIDEMISEENPLACE = "Aide à la mise en place d’enquêtes de terrain";
   public static final String CONSEILENINNOVATION = "Conseil en innovation sociale (réactions des usagers face aux innovations)";
   public static final String CONSEILENEMEDIATION = "Conseil en e-médiation ";
   public static final String AIDEALAMISEENPLACE = "Aide à la mise en place de programmes de prévention en matière de santé";
   public static final String ETUDEDESSAVOIRFAIRE = "Etude des savoir-faire et des pratiques anciennes pour l’aide à la conception de produits durables";
   public static final String[] CELINE = { "Mme", "Céline", "ROYET",
         "celine.royet@udamail.fr", "04 73 17 84 67" };

   public static final String ICCF = "http://iccf.univ-bpclermont.fr/";
   public static final String LAMP = "http://wwwobs.univ-bpclermont.fr/atmos/";
   public static final String LM = "http://math.univ-bpclermont.fr";
   public static final String LMV = "http://wwwobs.univ-bpclermont.fr/lmv/";
   public static final String LPC = "http://clrwww.in2p3.fr/";
   public static final String AME2P = "http://ame2p.univ-bpclermont.fr";
   public static final String GDEC = "http://www6.clermont.inra.fr/umr1095";
   public static final String GRED = "www.gred-clermont.fr";
   public static final String LMGE = "http://www.lmge.univ-bpclermont.fr";
   public static final String PIAF = "http://www6.clermont.inra.fr/piaf";
   public static final String RGM = "http://rgm.univ-bpclermont.fr/";
   public static final String IP = "http://ip.univ-bpclermont.fr";
   public static final String LIMOS = "http://limos.isima.fr";
   public static final String LAEPT = "http://laept.univ-bpclermont.fr";
   public static final String ACTE = "http://acte.univ-bpclermont.fr/";
   public static final String CELIS = "http://celis.univ-bpclermont.fr";
   public static final String CERAMAC = "http://ceramac.univ-bpclermont.fr/";
   public static final String CERHAC = "http://cerhac.univ-bpclermont.fr/";
   public static final String CHEC = "http://chec.univ-bpclermont.fr/";
   public static final String GEOLAB = "http://geolab.univ-bpclermont.fr";
   public static final String LAPSCO = "http://lapsco.univ-bpclermont.fr/";
   public static final String LRL = "http://lrl.univ-bpclermont.fr";
   public static final String PHIER = "http://phier.univ-bpclermont.fr";
   public static final String CRCGM = "http://www.crcgm.fr";

   public static final String OUI = "Oui";
   public static final String NON = "Non";
   public static final String EMPTY = "";
   public static final String TECHNOLOGIQUE = "Technologique";
   public static final String SHS = "SHS";
   public static final String LANGUAGE = "language";
   public static final String CIVILITY = "civility";
   public static final String FIRSTNAME = "firstname";
   public static final String SURNAME = "surname";
   public static final String PHONENUMBER = "phone_number";
   public static final String FAXNUMBER = "fax_number";
   public static final String EMAIL = "email";
   public static final String FUNCTION = "function";
   public static final String URL1 = "URL";
   public static final String FR = "fre-FR";

   public static final List<Integer> TO_CLEAN = Arrays.asList(351, 362, 370,
         376, 384, 391, 398, 404, 412, 438, 452, 460, 468, 478, 483, 492,
         501, 517, 524, 530, 548, 565, 572, 589, 597, 602, 651, 659, 667,
         680, 693, 704, 711, 717, 726, 741, 750, 760, 773, 790, 802, 819,
         827, 837, 852, 862, 871, 878, 891, 904, 909, 917);

   public static final List<Integer> TO_CLEAN1 = Arrays.asList(970, 990, 998,
         1011, 1026, 1032, 1044, 1058, 1066, 1076, 1093, 1103, 1110, 1115,
         1126, 1132, 1138, 1153, 1163, 1177, 1187, 1194, 1199, 1207, 1219,
         1228, 1241, 1245, 1252, 1270, 1279, 1287, 1292, 1297, 1302, 1306);

   public static final String[][] EQUIPE = {
         { "Synthèse et étude de systèmes à intérêt biologique (SEESIB)",
               "Photochimie", "Matériaux Inorganiques (MI)",
               "Thermodynamique des Interactions Moléculaires (TIM)",
               "Conception et synthèse de molécules antalgiques (CESMA)" },
         {
               "Processus physiques, chimiques et biologiques dans l’atmosphère nuageuse",
               "Nuages et précipitations à l’échelle des observations aéroportées et par télédétection",
               "Développement instrumental et expérimentation" },
         {
               "P.A.S.: Probabilités, Analyse, Statistique",
               "E.D.P.A.N.: Équations aux Dérivées Partielles et Analyse Numérique",
               "G.A.A.O.: Géométrie, Algèbre, Algèbres d’Opérateurs",
               "T.N.A.: Théorie des Nombres et Analyse" } };

   public static final String[] COMPETENCES = {
         "Volcanologie",
         "Pétrologie",
         "Géochimie",
         "Groupe de recherches en géologie appliquée et environnement",
         "Rôle et flux des éléments volatils dans les magmas",
         "Les mécanismes géodynamiques de la Terre primitive",
         NONAPPLICABLE,
         "Particule et univers - Matière hadronique - ATLAS",
         "Particule et univers - LHCB",
         "Particule et univers - D.O.",
         "Particule et univers - I.L.C.",
         "Particule et univers - ANTARES",
         "Particule et univers - Matière hadronique - ALICE",
         "Matière nucléaire - PHENIX",
         "Matière nucléaire - FOPI",
         "Matière hadronique - Sonde électromagnétique - SONDE EM",
         "Physique pour la santé et l'environnement - Imagerie de contrôle pour les irradiations par ions carbone - THEORIE",
         "Physique pour la santé et l'environnement - Développement et utilisation de grilles de calculs pour le médical et la biologie - AVIRM",
         "Physique pour la santé et l'environnement - Développement et utilisation de grilles de calculs pour le médical et la biologie - PCSV",
         "Physique pour la santé et l'environnement - PNAB",
         "Physique pour la santé et l'environnement - TL",
         NONAPPLICABLE,
         "Activité Physique et métabolisme énergétique",
         "Activité Physique, métabolisme et fonctionnalité musculo-squelettique",
         NONAPPLICABLE,
         "Structure, fonction, évolution des génomes du blé",
         "Paléogénomique des Plantes pour l’Amélioration Variétale",
         "Rendement et Adaptation du Blé aux contraintes abiotiques",
         "Biologie intégrative de la composition du grain",
         "Maladies des céréales",
         "Diversité génétique et sélection",
         NONAPPLICABLE,
         "SILENT–Silencing, Environment & Transposons",
         "Establishment, maintenance and transcriptional regulation of heterochromatin",
         "Genetic instabilities and control by the host genome",
         "Recombination and maintenance of the genome",
         "Genetic and epigenetic control of cell lineage commitment during mouse development",
         "Mechanisms of post-testicular infertility",
         "Diversification of muscle and heart cells in normal development and in pathological conditions",
         "Epithelial growth and morphogenesis",
         "Lipid, nuclear receptors and male disorders",
         "Adrenal tumours & adipose tissue homeostasis",
         NONAPPLICABLE,
         "Interactions hôtes-parasites",
         "Communautés microbiennes : écotoxicologie-santé",
         "Microbiologie de l’environnement et bioinformatique",
         "Virus et Métabolismes microbiens en milieu aquatique",
         "Interactions dans les réseaux trophiques aquatiques",
         NONAPPLICABLE,
         "Hydraulique et résistance à la sécheresse des arbres",
         "Contraintes Mécaniques et activité des zones en croissance",
         "Micro-Environnement et Arbre",
         NONAPPLICABLE,
         "Mécanismes et composants des systèmes de réparation de l’ADNmt",
         "Réparation de l’ADN mitochondrial et cancer",
         NONAPPLICABLE,
         "Image, Systèmes de Perception, Robotique",
         "Photonique, Ondes, Nanomatériaux",
         "Mécanique, Matériaux et Structures",
         "Génie des Procédés, Energétique et Biosystèmes",
         NONAPPLICABLE,
         "Modèles et Algorithmes de l’Aide à la Décision",
         "Systèmes d’Information et de Communication",
         "Outils Décisionnels pour la Production et la Logistique",
         "Recherche Opérationnelle pour le Génie Industriel",
         NONAPPLICABLE,
         "Calculs théoriques plasmas",
         "Rayonnement moléculaire",
         "Pieds d’arc, phénomènes aux électrodes",
         "Modélisation",
         "Appareillages de coupure",
         NONAPPLICABLE,
         "Situations de transmission de connaissances et d’apprentissage",
         "Dynamiques des interactions asymétriques",
         "Professionnalisation et métier",
         "Conception et évaluation d’outils et de dispositifs",
         NONAPPLICABLE,
         "Littératures et représentations de l’Antiquité et du Moyen-Âge",
         "Lumières et Romantismes",
         "Écritures et Interactions sociales",
         "Littératures 20/21",
         NONAPPLICABLE,
         "Innovation, patrimonialisation, valorisation des ressources",
         "Gouvernance, espaces intermédiaires, nouvelles territorialités",
         NONAPPLICABLE,
         "Le Centre d’Études et de Recherches sur la Réforme et la Contre-Réforme",
         "Le Centre International Blaise Pascal",
         "Équipe Imaginaire et Lettres du XVIe siècle",
         NONAPPLICABLE,
         "L’opposition dans la Cité : objets, acteurs, formes",
         "Dynamiques culturelles et artistiques",
         "Plaines et montagnes : sociétés et espaces du Massif Central. Structures, peuplement, patrimoine",
         "Circulation des hommes et des idées : histoire des connections politiques et culturelles",
         NONAPPLICABLE,
         "Paléoenvironnement et Géoarchéologie",
         "Dynamiques Géoenvironnementales Actuelles",
         "Capital Environnemental",
         NONAPPLICABLE,
         "Régulation sociale des cognitions et comportements",
         "Catégorisation sociale et relations entre groupes",
         "Émotion, affect et cognition",
         "Langage et cognition",
         NONAPPLICABLE,
         "Structures syntaxiques",
         "Processus de Développement de l’Écrit et de l’Oral en Langue maternelle et étrangère",
         "Sémantique, Pragmatique et Discours",
         "Dispositifs, Apprentissage en Ligne et Interactions",
         NONAPPLICABLE,
         "Histoire et philosophie de la connaissance, des sciences, de la logique et du langage",
         "Histoire des systèmes",
         "Raison et savoirs pratiques",
         NONAPPLICABLE,
         "« Mondes sociaux » des petites entreprises, ressources humaines et marché du travail",
         "Gouvernance, information et organisations responsables",
         "Management de la chaine de valeur et pilotage de la performance",
         "Management des situations extrêmes", NONAPPLICABLE };
   public static final String[] DOMAINES = {
         "Génie alimentaire",
         "Génie biologique",
         "Génie électrique",
         "Technologies de mesure",
         "électronique",
         "Optique / photonique",
         "Physique du signal",
         "Développement thérapeutique",
         "Diagnostic et marqueurs biologiques",
         "Outils de recherche biologiques et pharmaceutiques",
         "Matériaux non métalliques / technologies et procédés",
         "Matériaux métalliques / technologies et procédés",
         "Génie civil",
         "Génie énergétique et procédés thermiques",
         "Systèmes mécaniques",
         "Mécanique de précision",
         "Machines/équipements",
         "Transport du signal",
         "Multimédia",
         "Ingénierie",
         "Technologies logicielles de base",
         "Technologies logicielles pour applications et services informatiques",
         "Génie des procédés chimiques",
         "Biotechnologie blanche / biotechnique",
         "Ecotechnologies et procédés",
         SANTE,
         SPORT,
         AUTRE,
         "Génie alimentaire",
         "Génie biologique",
         "Génie électrique",
         "Technologies de mesure",
         "électronique",
         "Optique / photonique",
         "Physique du signal",
         "Développement thérapeutique",
         "Diagnostic et marqueurs biologiques",
         "Outils de recherche biologiques et pharmaceutiques",
         "Matériaux non métalliques / technologies et procédés",
         "Matériaux métalliques / technologies et procédés",
         "Génie civil",
         "Génie énergétique et procédés thermiques",
         "Systèmes mécaniques",
         "Mécanique de précision",
         "Machines/équipements",
         "Transport du signal",
         "Multimédia",
         "Ingénierie",
         "Technologies logicielles de base",
         "Technologies logicielles pour applications et services informatiques",
         "Génie des procédés chimiques",
         "Biotechnologie blanche / biotechnique",
         "Ecotechnologies et procédés", SANTE, SPORT, AUTRE };

   public static final String[] DISCIPLINES = { "Économie", "Finance",
         "Management et Ressources Humaines", "Droit",
         "Sciences politiques", "Sociologie", "Anthropologie", "Ethnologie",
         "Démographie", "Information et communication-médias",
         "Géographie physique",
         "Aménagement du territoire-urbanisme- Habitat",
         "Sciences cognitives",
         "Sciences du langage – linguistique générale", "Psychologie",
         "Sciences de l’éducation (Education, Pédagogie, Enseignement)",
         "Langues", "Littérature",
         "Arts (plastiques, du spectacle, musique, visuels)", "Philosophie",
         "Religion et Histoire des idées", "Préhistoire", "Archéologie",
         "Histoire", SANTE, SPORT };

   public static final String[] SOUS_DOMAINES = {
         "Développement de produits de la conception à l’industrialisation",
         "Formulation/recette",
         "Séchage",
         "Cuisson et cuisson-extrusion",
         "Réfrigération et congélation",
         "Broyage/fragmentation",
         "Mélange et pétrissage",
         "Séparation/extraction",
         "Technologies de préparation/tri/découpe",
         "Nutrition/aliment santé",
         "Sensoriel",
         "Hygiène",
         AUTRE,
         "Sélection/reproduction animale",
         "Sélection/reproduction végétale",
         "Lutte biologique",
         "Stimulation des mécanismes naturels des plantes",
         "Fermentation agroalimentaire",
         "Traitements biologiques et microbiologiques pour l’environnement (dont méthanisation)",
         "Autres traitements microbiologiques",
         "Itinéraires agronomiques",
         "Enzymologie",
         "Composés/Matériaux à partir du vivant",
         AUTRE,
         "Machines de production d’électricité/générateurs/transformation",
         "Technologie de stockage d'électricité : batterie, super-condensateur ...",
         "Technologies de distribution d’électricité",
         "élaboration/utilisation de systèmes électriques",
         "Utilisation des propriétés électriques (piézoélectricité/électromagnétisme/électrostatique/supraconductivité)",
         "Technologies liées à la sécurité électrique",
         "Technologies douces (lumière pulsée, champs électriques/magnétiques pulsés, plasma, ...)",
         AUTRE,
         "Mesure/contrôle/analyse",
         "Mesure pour l’automatisme/pour l’électronique",
         "Technologies de métrologie (électrique, optique, magnétique, rayonnement, ultrason)",
         "Capteurs",
         "Contrôle non destructif",
         AUTRE,
         "Composants actifs et passifs (puce, FPGA, ASIC, SoC, mémoire, microprocesseur, ...)",
         "Cartes à puce - étiquettes électroniques - RFID",
         "Composants MEMS/NEMS",
         "Conception électronique : cartes, systèmes, produits",
         "Procédés/techniques de fabrication microélectronique   (procédés de fabrication, intégration 3D, équipements dédiés : implantation, CMP ...)",
         "électronique organique (composants et circuits)",
         "Nanotechnologies, procédés relevant de la nanoélectronique",
         AUTRE,
         "Développement/utilisation de fibres optiques",
         "Laser : cavités, systèmes",
         "Composants optiques, connectique optique, MOENS (microsystème optique)",
         "Imagerie",
         "Technologies d'affichage/d'éclairage LED, OLED, LCD, TFT, ...",
         "Technologies de visualisation (UV, visible, infrarouge, multispectrale), caméra, holographie",
         AUTRE,
         "Acoustique",
         "Ultrasons",
         "Rayonnement, radioactivité, RMN",
         "Radiofréquences et microondes, radar",
         "Spectroscopie/spectrométrie",
         "Traitement du signal (filtrage ...)",
         AUTRE,
         "Principe actif chimique",
         "Biomédicament",
         "Thérapie génique et cellulaire",
         "Vaccins préventifs",
         "Vectorisation",
         AUTRE,
         "Biomarqueurs génétiques",
         "Biomarqueurs protéiques",
         "Méthodes de détection",
         AUTRE,
         "Criblage",
         "Modèles cellulaires et animaux",
         "Réactifs",
         AUTRE,
         "Procédés de mélange/homogénéisation",
         "Procédés thermiques/thermolyse/incinération/vitrification",
         "Synthèse et croissance cristalline",
         "Bois et cellulose",
         "Cuir",
         "Élaboration de non tissé",
         "Elastomères/caoutchoucs",
         "Ennoblissement, Teinture, Impression",
         "Filature",
         "Matériaux biomimétiques",
         "Matériaux biosourcés",
         "Matériaux composites et textiles",
         "Polymères",
         "Matériaux intelligents ou adaptatifs",
         "Nanomatériaux non métalliques",
         "Papier/carton",
         "Préparation des fibres",
         "Imprégnation",
         "Découpe et Usinage",
         "Procédés de transformation et d'assemblage",
         "Prototypage rapide",
         "Technologie des poudres",
         "Tissage, Tricotage, Tressage",
         "Traitements de surface/revêtements",
         "Verres et céramiques",
         AUTRE,
         "Acier, alliages à hautes performances (mécaniques, thermiques, ...)",
         "Découpe et Usinage",
         "Formulation et elaboration des matériaux ferreux",
         "Formulation et élaboration des matériaux non ferreux",
         "Métallurgie des poudres , fusion…",
         "Métaux ferreux",
         "Métaux non ferreux (aluminium, plomb, cuivre zinc, étain, ...)",
         "Métaux précieux",
         "Moulage, forgeage, estampage, matriçage, emboutissage, ...",
         "Nanomatériaux métalliques",
         "Procédés d’assemblage",
         "Prototypage rapide",
         "Traitements de surface/revêtements/marquage",
         AUTRE,
         "Technologies du sol",
         "Technologies du sous-sol",
         "Technologies de la mer/offshore",
         "Élaboration/utilisation de matériaux de construction",
         "Technologies de construction",
         "Modélisation et bâtiment virtuelle",
         "Équipements d’exploitation du gaz/charbon/pétrole/géothermie",
         AUTRE,
         "Production/utilisation d’hydrocarbures/charbon",
         "Production/utilisation d’énergie nucléaire",
         "Production/utilisation d’énergies renouvelables (hydraulique,solaire,photovoltaïque,éolien,géothermie,énergie marémotrice)",
         "Stockage d’énergie",
         "Production/utilisation de chaleur",
         "Technologies du froid",
         "Technologies liées à la pile à combustible/Production d’hydrogène",
         AUTRE,
         "Matériels/Équipements de transport",
         "Composants automobiles (frein, embrayage, réducteur, amortisseur, ...)",
         "Moteurs thermiques/moteurs hybrides",
         "Système Hydraulique/Pneumatique",
         "Équipements mécaniques divers (robinetterie/quincaillerie ...)",
         "Système de sécurité",
         "Système de fixation",
         "Système d'amortissement",
         "Conception/fabrication d’appareils domestiques/biens de consommation/mobiliers",
         AUTRE,
         "Matériel médical de précision (instrumentation, prothèses, valves, stents ...)",
         "Micromécanique/micromoteur",
         "Horlogerie-optique (partie mécanique)",
         "Autres équipements de précision",
         AUTRE,
         "Outillage de Machines-outils",
         "Équipement de contrôle/Métrologie",
         "Équipement Robotisation/Automatisation/Manutention",
         "Équipement et Techniques du vide",
         "Équipement de validation Essais/tests mécaniques",
         "Équipement divers (outils de réglage, démontage, support…)",
         "Machines spéciales",
         "Machines de production tous secteurs",
         AUTRE,
         "Outillage de Machines-outils",
         "Équipement de contrôle/Métrologie",
         "Équipement Robotisation/Automatisation/Manutention",
         "Équipement et Techniques du vide",
         "Équipement de validation Essais/tests mécaniques",
         "Équipement divers (outils de réglage, démontage, support…)",
         "Machines spéciales",
         "Machines de production tous secteurs",
         AUTRE,
         "Outils de création, production et distribution de contenus multimédias",
         "Outils création, production, diffusion simultanément sur plusieurs médias",
         "Asset management et gestion collaborative de production de contenus",
         "Outils d'indexation et recherche sémantique",
         "Reconnaissance et synthèse de la parole/écriture/formes/sons/images",
         "Outil de spatialisation sonore",
         "Technologies 3D/relief",
         "Interfaces (IHM) immersives",
         "Outil de réalité virtuelle",
         "Outils d'intelligence artificielle (animation, interaction, jeu)",
         "Moteur de jeux vidéo",
         "Technologies de traitement de l'image et du son",
         "Technologies d'encodage et de compression",
         "Protection de contenu et gestion de droits (DRM, tatouage d’images, de flux vidéo)",
         "Protection des données privées",
         AUTRE,
         "Conception de produits",
         "Gestion/technologies organisationnelles",
         "Méthodologie",
         "Ergonomie/design",
         "Contrôle qualité",
         "Maintenance",
         AUTRE,
         "Ingénierie logicielle - Outils et méthodes de développement",
         "Infrastructure, réseaux et protocoles, OS, middleware et composants logiciels",
         "Données et Bases de données",
         "Technologies d'interface et d'Interaction",
         "Sécurité des Systèmes Informatiques (Réseaux - Contenus - SI)",
         AUTRE,
         "Acquisition, traitement et échanges de données",
         "Aide à la décision - Intelligence artificielle",
         "Applications horizontales (génériques, transversales)",
         "Applications verticales (sectorielles / métiers)",
         "Bureautique",
         "eCommerce, eMarketing et publicité en ligne",
         "Gestion de process, optimisation économique et business models",
         "Gestion et diffusion de contenus numériques, collaboration et gestion de la connaissance",
         "Green IT et développement durable",
         "Imagerie scientifique et technologies de visualisation (réalité virtuelle, augmentée, 3D)",
         "Interactions et interfaces",
         "Logistique et traçabilité",
         "Mobilité et géolocalisation",
         "Dématérialisation et Transactions électroniques sécurisées",
         "Services Web innovants et internet mobile",
         "Simulation, modélisation, CAO, calcul intensif et HPC",
         "Systèmes embarqués et logiciels enfouis, temps réel, critiques",
         AUTRE,
         "Biochimie",
         "Catalyse",
         "Détermination structurale 3D (cristallisation, ...)",
         "Développements de colorants/pigments/agents tannants et autres produits",
         "Développements de produits biocompatibles",
         "Développements de produits biodégradables",
         "Développements de produits pour l’agrochimie",
         "Formulation",
         "Modélisation/simulation moléculaire",
         "Procédés de séparation/extraction",
         "Technologies d’extraction",
         "Technologies de production (microencapsulation, …)",
         "Technologies de séparation/purification/filtration",
         "Traitements physico-chimiques",
         "Valorisation de produit/sous-produit",
         "Chimie des produits biosourcés",
         AUTRE,
         "Bioconversion",
         "Digestion microbienne",
         "Fermentation aérobie",
         "Fermentation anaérobie",
         "Biosynthèse",
         "Catalyse enzymatique/biocatalyse",
         AUTRE,
         "Valorisation de déchets et/ou sous-produits",
         "Valorisation biomasse",
         "Écoconception / Analyse de cycle de vie",
         "Recyclage",
         "Évaluation/Prévention des risques sanitaires",
         "Évaluation/Prévention des risques industriels",
         "Évaluation/Prévention des risques naturels",
         "Techniques préventives limitant l’émission de COV (Composés Organiques Volatils)",
         "Technologies sans solvants organiques",
         "Analyse des paramètres physico-chimiques de l’eau",
         "Analyse des paramètres biologiques de l’eau",
         "Télégestion et surveillance des réseaux d’eau",
         "Compostage",
         "Biodiversité",
         "Technologies de recyclage",
         "Systèmes actifs de réduction du bruit",
         AUTRE,
         "Expertise en matière d’éducation thérapeutique",
         "Études en matière des troubles de la communication et de la mémorisation",
         AIDEALAMISEENPLACE,
         "Développement d’outils et d’instruments de diagnostic de maladies chroniques",
         "Expertise sur le statut et le rôle du patient dans le traitement des maladies",
         "Expertise en hygiène et sécurité alimentaire",
         "Expertise et gestion des risques sanitaires",
         AUTRE,
         "Conseil en Marketing sportif",
         "Aide dans la conception de gammes d’articles de sport et de loisirs",
         "Conseil en organisation et management d’entreprise du secteur sportif",
         "Conseil sur les pratiques sportives en entreprise - expertise en matière de sport en entreprise",
         AUTRE };
   public static final String[] SOUS_DISCIPLINES = {
         "Théorie économique et histoire économique y compris les méthodes mathmatiques et quantitatives",
         "Expansion économique, planification du développement, inflation",
         "Econométrie, statistiques économiques",
         "Microéconomie",
         "Théorie monétaire et fiscale, politique, institutions",
         "Macroéconomie et économie monétaire",
         "Economie internationale, financière, des affaires, des finances commerciales",
         "Economie des Ressources naturelles, environnement, énergie",
         "Economie agricole",
         "Economie du travail et démographie",
         "Droit et économie publique",
         "Organisation industrielle et systèmes économiques",
         "Education et bien-être",
         "Economie urbaine, rurale",
         "Economie de la santé",
         "Economie touristique",
         "Développement de modèles multi-agents pour l’analyse des politiques économiques",
         "Aide à l’internationalisation d’entreprise",
         "Evaluation des politiques publiques",
         "Analyse économique des contrats de distribution",
         "Etude des comportements microéconomiques des ménages en matière d’emploi, de santé et d’éducation, à l’aide de méthodes économétriques avancées",
         AUTRE,
         "Finance d'entreprise",
         "Finances des marchés et mondialisation",
         "Finances publiques",
         "Conseil en gestion des risques financiers",
         "Conseil en intermédiation financière",
         "Expertise en protection financière",
         "Expertise sur les évolutions de la gestion d’actifs",
         AUTRE,
         "Fonction de Gestion (planification, organisation, pilotage et leadership)",
         "Gestion (comptable et financière)",
         "Gestion des services de l’organisation (service commercial, marketing et vente, financier, production)",
         "Relations entre management et d’autres concepts (management et gouvernance, et pédagogie, par ex.)",
         "Expertise en gouvernance d'entreprise et gestion des ressources humaines",
         "Expertise en matière de changement professionnel",
         "Conseil en négociation collective et interprofessionnell",
         AUTRE,
         "Droit administratif, civil et commercial",
         "Droit comparé, Common law - Droit des biens communs",
         "Droit pénal, Droit de la famille, Droits de la personne, Droit de la santé",
         "Droit international, Droit du travail, Droit fiscal",
         "Droit public, Droit de la consommation, Droit de l'environnement, Droit maritime",
         "Propriété industrielle et intellectuelle - Expertise juridique en matière de copyright et de droit d’auteur dans l’industrie culturelle",
         "Philosophie du droit et Histoire du Droit",
         "Droits des médias et des communications",
         "Conseil juridique en entreprise",
         "Conseil en gestion du patrimoine",
         "Expertise dans le domaine de la protection sociale",
         "Aide à la conformité avec les normes juridiques européennes",
         AUTRE,
         "Politique comparée",
         "Études constitutionnelles",
         "Gouvernement et administration publique",
         "Relations internationales et Géopolitique",
         "Économie politique",
         "Partis politiques, études électorales",
         "Pensée et théories politiques",
         "Aide à la décision en matière de politique sociale et urbaine",
         "Evaluation des politiques publiques",
         "Aide à l’internationalisation des entreprises",
         "Etude des politiques européennes",
         "Expertise en matière d'analyse du marché de l'emploi",
         AUTRE,
         "Institutions sociales",
         "Processus sociaux -Interactions sociales",
         "Structures sociales",
         "Sociologie appliquée à des thématiques",
         "Outils et méthodes de la sociologie (statistiques et sondages)",
         "Expertise en matière d'analyse du marché de l'emploi",
         AIDEMISEENPLACE,
         "Conseil en adaptation socio-culturelle",
         "Diagnostic des représentations sociales",
         CONSEILENINNOVATION,
         AUTRE,
         "Anthropologie des sociétés modernes",
         "Études comparatives et transculturelles",
         AIDEMISEENPLACE,
         "Aide à la conception de produits (analyse des usages et des habitudes des particuliers)",
         CONSEILENINNOVATION,
         "Aide à la connaissance des pratiques culturelles",
         AUTRE,
         "Ethnographie",
         AIDEMISEENPLACE,
         "Aide à la conception de produits (analyse des usages et des habitudes des particuliers)",
         CONSEILENINNOVATION,
         "Aide à la connaissance des pratiques culturelles",
         AUTRE,
         "Vieillissement, gérontologie sociale",
         "Migration, mobilité",
         "Dynamique des populations",
         "Expertise dans les migrations internationales",
         "Conseil en développement durable",
         "Analyse des pratiques de mobilité",
         "Modélisation des flux de transport",
         "Modélisation des mobilités résidentielles des espaces publics",
         AUTRE,
         "Etudes des médias, moyens de communication de masse (dont radio et télévision)",
         "Stratégie politique, opinion publique",
         "Journalisme",
         "Analyse du discours et des messages médiatisés",
         "Théorie de l’Information et de la Communication",
         "Information scientifique et technique",
         "Edition, presse (Histoire des livres, de l'édition, de la presse, Industrie du livre)",
         "Nouveaux médias, Internet, web",
         "Bibliothéconomie-Science de l’information (Bibliographie, Collections : acquisition, catalogage, classification)",
         "Conseil en e-médiation",
         "Conseil en optimisation de la gestion des données en entreprise, notamment par l’usage et le développement des TIC",
         "Conseil en conception et ergonomie des interfaces numériques (de la création littéraire au design d’interface)",
         "Développement d’outils liés aux technologies de l’information (moteurs de recherche, hypertextes, hypermédias, outils informatiques, etc.)",
         "Aide à l’amélioration et à la conception de dispositifs d’information et de communication",
         AUTRE,
         "Géographie",
         "Utilisation des sols",
         "Géographie des ressources naturelles",
         "Géomorphologie",
         "Analyse des changements dans les espaces urbains et métropolitains",
         "Modélisation et cartographie dynamiques et multi-échelles",
         "Analyse de processus de production des espaces du passé comme du présent",
         "Réalisation de systèmes d’informations géographiques",
         AUTRE,
         "Écologie humaine",
         "Gestion des ressources",
         "Planification territoriale",
         "Logement-Habitat",
         "Diagnostic des vulnérabilités au changement climatique et conseil en adaptation des territoires",
         "Conseil en développement durable : développement d’outils et analyse des stratégies de gouvernance",
         "Aide à la décision en matière de politique de la ville",
         "Conseil en aménagement et en gestion des réseaux de transport",
         "Conseil en gestion durable de l’eau",
         AUTRE,
         "Psychologie cognitive",
         "Apprentissage",
         "Mémoire (verbale, visuelle, auditive, tactile)",
         "Gestion de la Connaissance",
         "Ergonomie cognitive",
         "Intelligence artificielle (voir aussi sciences et techniques)",
         "Développement d’outils et d’instruments de diagnostic de troubles mentaux et psychologiques",
         "Evaluation de traitements alternatifs des maladies neurologiques",
         "Audit de stress et de bien-être en entreprise",
         "Aide à conception de produits alimentaires",
         "Etudes en matière des troubles de la communication et de la mémorisation (maladie d’Alzheimer et schizophrénie)",
         "Expertise en matière de comportement de consommation",
         AUTRE,
         "Linguistique diachronique, histoire de la linguistique, Théories de la linguistique, dialectologie",
         "Grammaire, syntaxe",
         "Acquisition du langage, interaction des langues",
         "Lexicologie, lexicographie",
         "Morphologie, Phonétique, phonologie",
         "Psycholinguistique, Sociolinguistique",
         "Linguistique appliquée, Linguistique comparée, Linguistique générale",
         "Traduction et interprétation, Écritures",
         "Bilinguisme, apprentissage des langues secondes",
         "Sémiologie, Génétique des langues, classification, parenté",
         "Aide à l’optimisation de dispositifs d’apprentissage par l’usage des TIC",
         "Etudes en matière des troubles de la communication et de la mémorisation (maladie d’Alzheimer et schizophrénie)",
         "Développement d’une base de données de ressources linguistiques",
         "Conseil en pathologie du langage chez les personnes atteintes de la maladie d’Alzheimer ou de bégaiement",
         "Analyse des usages du langage et de ses évolutions",
         "Conseil en pédagogie numérique adaptée à des publics spécifiques (publics empêchés)",
         AUTRE,
         "Psychologie du comportement, du développement humain",
         "Psychologie de l'enfance et de l'adolescence",
         "Psychologie de l'éducation, du sport, sociale",
         "Histoire de la psychologie",
         "Sexologie",
         "Aspects psychologiques de la médecine et des soins de santé (thérapies : psychothérapie, psychothérapie…)",
         "Audit de stress et de bien-être en entreprise",
         "Développement d’outils et d’instruments de diagnostic de troubles mentaux et psychologiques",
         "Evaluation de traitements alternatifs des maladies neurologiques",
         AIDEALAMISEENPLACE,
         "Conseil en innovation sociale",
         AUTRE,
         "Éducation bilingue, enseignement de la langue seconde",
         "Éducation comparée, professionnelle, Formation professionnelle et continue",
         "Enseignement et apprentissage assistés par ordinateur- Enseignement à distance",
         "Conseils et orientation professionnelle",
         "Institutions éducatives (administration, directions scolaires, etc.)",
         "Histoire, philosophie et théories de l'éducation, éducation comparée, sociologie de l'éducation",
         "Formation des maîtres et des enseignants, Méthodes d'enseignement, pédagogie,",
         "Organisation et fonctionnement des systèmes éducatifs",
         "Education spécialisée (enfants précoces, handicaps)",
         "Mesure et évaluation",
         "Aide à l’optimisation de dispositifs d’apprentissage par l’usage des TIC",
         "Aide à l’optimisation des dispositifs d’apprentissage en formation de l’enfant",
         "Evaluation des politiques publiques d’éducation",
         "Conseil en pédagogie numérique adaptée à des publics spécifiques (publics empêchés)",
         "Conseil en apprentissage autodirigé",
         "Conseil en gestion de crise en milieux scolaire et éducatif",
         AUTRE,
         "Études langues anciennes et langues classiques et mortes",
         "Langues médiévales, minorisées menacées d’extinction",
         "Langues modernes",
         "Langues étrangères (espagnol, portugais, italien, slaves, allemande et germaniques, anglaise, anglo-américain)",
         "Conception de bases de données, de logiciels, et d’applications informatiques permettant l’étude de la langue",
         "Aide à la réalisation d’outils informatiques en matière de traitement linguistique et d’exploitation de corpus",
         "Traduction de textes",
         AUTRE,
         "Littérature et ancien français et langues anciennes et mortes (grec, latin…) et Civilisations",
         "Littératures et langues modernes",
         "Littératures française   générale, comparée",
         "Littératures et langues étrangères (anglaise, allemande, américaine, romane, slave)",
         "Littérature - Études bibliographiques, Critique littéraire, Genres littéraires, Tendances littéraires, Formes et théories littéraires, Thèmes et personnages",
         "Développement d’outils liés aux technologies de l’information : moteurs de recherche, hypertextes, hypermédias, outils informatiques, etc.",
         "Développement d’une base de données de ressources linguistiques",
         "Aide à l’élaboration de dictionnaires électronique",
         "Conseil en médiation",
         AUTRE,
         "Esthétique",
         "Architecture, Sculpture-Arts plastiques",
         "Cinéma, études cinématographiques et vidéo",
         "Danse, Musique, Musicologie, Théâtre, Peinture, Photographie",
         "Arts visuels : arts décoratifs, mode, bande dessinée.",
         "Arts numériques : réalité virtuelle, réalité augmentée, Net-Art",
         "Création littéraire, poésie",
         "Cuisine",
         "Arts multidisciplinaires et interdisciplinaires (dont design)",
         "Développement de prototypes artistiques numériques interdisciplinaires et interactifs originaux dans le but de favoriser une meilleure interaction des œuvres et des installations artistiques avec le spectateur",
         "Etude des changements de perception, d’action et de cognition du public en rapport avec les nouvelles formes d’espace et de temporalité induites par les pratiques artistiques actuelles",
         "Modélisation/restitution par image interactive des diverses formes de relations existantes entre le public et les œuvres (désignation, consultation, perception sensible, manipulation, etc.)",
         "Aide à la programmation, à la composition et à la synthèse de sons",
         "Conseil en esthétique audiovisuelle",
         AUTRE,
         "Philosophie analytique, philosophie linguistique",
         "Phénoménologie, existentialisme",
         "Épistémologie, Histoire de la philosophie, Logique",
         "Éthique, Bioéthique, Éthique de l'environnement, Éthique des sciences et de la technologie, Éthique de la santé",
         "Métaphysique",
         "Philosophie de l'éducation, de la santé, du droit",
         "Elaboration de méthodes d’apprentissage pour l’adulte et l’enfant",
         "Etude de la traçabilité numérique et de ses enjeux éthiques, politiques, économiques, culturels, symboliques et sociétaux",
         "Conseil en bioéthique",
         AUTRE,
         "Études religieuses , Théologie",
         "Religions anciennes, Études monastiques médiévales",
         "Histoire de l'Église, Droit canonique,",
         "Histoire et Philosophie de la religion",
         "Religion comparée et Religions orientales, Judaïsme, Études islamiques",
         "Études bibliques (écriture sainte, Ancien Testament, Nouveau testament)",
         "Conseil en adaptation socio-culturelle",
         "Aide à la décision en matière de politique sociale et urbaine",
         AUTRE,
         "Chasse et cueillette",
         "Origines et développement de l'agriculture",
         "Aide à la conception d’outils de médiation pour l’enseignement de la préhistoire",
         "Expertise géoarchéologique et géologique",
         CONSEILENEMEDIATION,
         ETUDEDESSAVOIRFAIRE,
         AUTRE,
         "Archéologie générale et classique   : théories et méthodes",
         "Architecture, art, iconographie, Technologie, fabrication d'outils",
         "Civilisations primitives (origines, dévelop., urban.)",
         "Histoire et philosophie de l'archéologie, rech. préhist.",
         "Archéologie de l'environnement, maritime",
         "Paléoanthropologie, ethnoarchéologie, paléoethnologie",
         "Courants de peuplement, utilisation des sols, paléodémographie.",
         "Commerce et routes commerciales, contacts culturels",
         "Aide à la conception d’outils de médiation pour l’enseignement",
         "Expertise géoarchéologique et géologique",
         CONSEILENEMEDIATION,
         ETUDEDESSAVOIRFAIRE,
         AUTRE,
         "Histoire du commerce, Histoire culturelle, Histoire économique, Relations internationales",
         "Historiographie",
         "Histoire de la médecine, Histoire des sciences et de la technologie",
         "Histoire des idéologies, Histoire politique, Histoire militaire",
         "Histoire du travail, Histoire sociale, Histoire urbaine, régionale, locale",
         "Instruments de recherche et méthodologie",
         "Histoire du genre, féminisme",
         "Histoire des services de santé, Histoire de l'éducation, Histoire de l'environnement",
         "Antiquité, Moyen-Age, Renaissance, Histoire moderne, Histoire contemporaine – 20e siècle",
         "Aide à la conception d’outils de médiation pour l’enseignement",
         CONSEILENEMEDIATION,
         ETUDEDESSAVOIRFAIRE,
         AUTRE,
         "Conseil en Marketing sportif",
         "Aide dans la conception de gammes d’articles de sport et de loisirs",
         "Conseil en organisation et management d’entreprise du secteur sportif",
         "Conseil sur les pratiques sportives en entreprise - expertise en matière de sport en entreprise",
         AUTRE,
         "Expertise en matière d’éducation thérapeutique",
         "Études en matière des troubles de la communication et de la mémorisation",
         AIDEALAMISEENPLACE,
         "Développement d’outils et d’instruments de diagnostic de maladies chroniques",
         "Expertise sur le statut et le rôle du patient dans le traitement des maladies",
         "Expertise en hygiène et sécurité alimentaire",
         "Expertise et gestion des risques sanitaires", AUTRE };

   public static final String[] SECTEURS = { "AERIEN",
         "AGRICULTURE -PECHE -AQUACULTURE",
         "AUDIOVISUEL -MULTIMEDIA -JEU VIDEO", "AUTOMOBILE", "BATIMENT",
         "BIOPROCEDES INDUSTRIELS (chimie)",
         "BIOTECHNOLOGIES (verte,marine,industrielle)",
         "BOIS -PAPIER -IMPRESSION", "CHIMIE", "COSMETOLOGIE",
         "ECO TECHNOLOGIES ENVIRONNEMENTALES",
         "EDITION DE LOGICIELS ET SERVICES INFORMATIQUES",
         "ELECTROTECHNIQUE", "ELECTRONIQUE", "EMBALLAGE -CONDITIONNEMENT",
         "ENERGIES", "EQUIPEMENT INFORMATIQUE", "FERROVIAIRE",
         "INDUSTRIE ALIMENTAIRE",
         "INDUSTRIE MECANIQUE -PROCESSUS INDUSTRIEL", "MANUTENTION",
         "MATERIAUX DE CONSTRUCTION", "MESURE -CONTROLE",
         "METALLURGIE -TRAVAIL DES METAUX", "NAVAL", "PARACHIMIE",
         "PHARMACIE -BIOINDUSTRIE", "PLASTIQUES -CAOUTCHOUCS", "SECURITE",
         "TECHNOLOGIES MEDICALES", "TELECOMMUNICATIONS",
         "TEXTILE -HABILLEMENT -CUIR -CHAUSSURE", "THERMIQUE",
         "TIC ET SERVICES", "TRAVAUX PUBLICS", "VERRES ET CERAMIQUE", AUTRE };
   public static final String[] SOUS_SECTEURS = {
         "Sylviculture",
         "Culture de céréales/cultures industrielles",
         "Horticulture (fruits, légumes, fleurs,...)",
         "Viticulture",
         "Produits fertilisants (engrais, biofertilisant)",
         "Produits phytosanitaires",
         "Semences et Plants",
         "Outils d'aide à la décision pour l'agriculture",
         "Équipements multifilières agricoles",
         "Élevage",
         "Équipements pour l'élevage",
         "Pisciculture-Aquaculture",
         "Pêche",
         "Équipements pour le secteur Pêche-Aquaculture",
         "Services pour le secteur agriculture",
         AUTRE,
         "Viande et produits carnés",
         "Poisson et produits de la mer",
         "Fruits/légumes transformés",
         "Corps gras",
         "Produit laitier, glace",
         "Ovoproduit",
         "Grain, farine, céréales transformées",
         "Alimentation animale",
         "Boissons (hors jus de fruits)",
         "PAI (produit alimentaire intermédiaire) : ingrédients, additifs, arômes, colorants",
         "Boulangerie, viennoiserie, pâtisserie et pâtes",
         "Sucre, confiserie, chocolat",
         "Diététique (aliments infantiles, régimes spéciaux, compléments alimentaires,...)",
         "Condiments, épices",
         "Plats cuisinés",
         "Mesure-contrôle pour les IAA (sécurité, traçabilité, analyses, chaîne du froid,...)",
         "Machines/équipements pour les IAA",
         "Services pour les IAA",
         "Équipements pour la distribution alimentaire et la restauration hors foyer",
         AUTRE,
         "Éclairage/affichage lumineux",
         "Piles/accumulateurs/batteries",
         "Moteur électrique/asservissement moteur",
         "Transformateur/convertisseur",
         "Matériel de distribution et de commande électrique/câblage",
         "Équipements pour le secteur électrotechnique",
         "Services pour le secteur électrotechnique",
         AUTRE,
         "Composants actifs et passifs (dont optiques)",
         "Matériaux pour composants électroniques",
         "Capteurs/microsystèmes/biopuces/microsources d’énergie",
         "Cartes à puce/étiquettes",
         "Écrans",
         "Équipements/tests pour fabrication de composants",
         "Optique/optoélectronique",
         "Connectique",
         "Circuits imprimés",
         "Conception de systèmes et sous-systèmes électroniques",
         "Électronique grand public",
         "Équipements pour la fabrication de produits électroniques",
         AUTRE,
         "Autres spécialités médicales",
         "Cancérologie",
         "Cardiovasculaire-hématologie",
         "Dermatologie - soin des plaies",
         "Endocrinologie",
         "Équipement-services",
         "Gynécologie-nephro-urologie",
         "Hépato-gastro-entérologie",
         "Inflammation-allergie",
         "Maladies infectieuses-parasitologie",
         "Neurologie",
         "Ophtalmologie",
         "ORL-Pneumologie",
         "Vétérinaire",
         AUTRE,
         "Matière première-principe actif",
         "Soin et Hygiène corporels",
         "Maquillage-Parfumerie",
         "Appareils et accessoires",
         "Services pour le secteur cosmétologie",
         AUTRE,
         "Suppléance fonctionnelle externe et Handicap (hors télésanté)",
         "Dispositif de délivrance de médicament et de thérapie",
         "Dispositifs de mesure, monitorage",
         "Imagerie diagnostique/interventionnelle",
         "Équipement et robotique médicochirurgicaux",
         "Paramédical / dispositifs de confort",
         "Prothèses - Implants - Matériaux de substitution",
         "Télésanté",
         "Instruments médicochirurgicaux - consommables",
         "Stérilisation/hygiène/protection/traçabilité",
         "Diagnostic in vitro",
         AUTRE,
         "Emballage bois",
         "Emballage papier/carton",
         "Emballage plastique",
         "Emballage verre",
         "Emballage métal",
         "Emballage intelligent",
         "Emballage Actif",
         "Emballage biosourcé",
         "Packaging (conception, impression, design)",
         "Sécurité/traçabilité/inviolabilité",
         "Équipements pour le secteur emballage/conditionnement",
         "Services pour le secteur emballage-conditionnement",
         "Recyclage, Réutilisation, valorisation des déchets",
         AUTRE,
         "Panneaux en bois",
         "Sciage et préparation du bois",
         "Articles divers en bois",
         "Pâte à papier, papier, carton",
         "Articles divers en papier-carton",
         "Impression",
         "Affichages publicitaires",
         AUTRE,
         "Fibres",
         "Chaussure",
         "Ennoblissement : teinture, impression, apport de fonctionnalités",
         "Filature-Tissage-Tricotage",
         "Habillement",
         "Non tissés",
         "Tannerie/articles en cuir",
         "Textiles à usage domestique : linge de maison, ameublement, tapis, moquette",
         "Textiles à usage technique",
         AUTRE,
         "Sidérurgie (1ère transformation de l’acier)",
         "Métaux précieux",
         "Transformation de l’acier (produits étirés, laminés ou formés à froid)",
         "Aluminium",
         "Plomb, zinc, étain (production et 1ère transformation)",
         "Cuivre (production et 1ère transformation)",
         "Titane",
         "Superalliages (à base de nickel ou de cobalt)",
         "Autres métallurgies",
         "Fonderie/Forge (fonte, acier et métaux non ferreux)",
         "Chaudronnerie/tuyauterie",
         "Outillage, coutellerie, quincaillerie",
         "Visserie, boulonnerie",
         "Autres activités travail des métaux (moule,...)",
         "Équipements pour le secteur métallurgie-travail des métaux",
         "Services pour le secteur métallurgie-travail des métaux",
         AUTRE,
         "Verre plat (fabrication, façonnage et transformation)",
         "Articles techniques en verre et céramique",
         "Fibres   verre et céramique",
         "Verre creux (sauf emballage)/verrerie de ménage/cristallerie",
         "Équipements spécifiques (cuisson, découpe, mise en forme)",
         "Céramiques réfractaires (pièce de forme et revêtements)",
         "Céramiques techniques",
         "Art de la table, vaisselle/verrerie de ménage/cristallerie",
         "Services pour le secteur verre et céramique",
         AUTRE,
         "Matières plastiques (formulation, synthèse et conditionnement de polymères, d’agents de polymérisation, d’additifs,...)",
         "Plasturgie (fabrication de produits semi-finis, articles divers, pièces techniques y compris matériaux composites)",
         "Élastomères/caoutchoucs (à usage général ou spécial)",
         "Transformation des caoutchoucs (pneumatiques, rechapage, caoutchouc industriel)",
         "Équipements pour le secteur plastiques-caoutchoucs",
         "Matériaux biosourcés dans les plastiques et caoutchouc",
         AUTRE,
         "Extraction de matériaux et minéraux pour la construction",
         "Matériaux naturels (ardoise, pierre, sable, argile, marbre)",
         "Matériaux industriels (tuile, brique,...)",
         "Béton ciment plâtre et chaux",
         AUTRE,
         "Structures/enveloppes (éléments porteurs, parois extérieures, couverture)",
         "Distribution des locaux/ organisation intérieure (cloisons)",
         "Aménagement extérieur (mobilier urbain, bassin)",
         "Aménagement intérieur (mobilier,...)",
         "Revêtement sol/mur",
         "Appareils sanitaires",
         "Menuiserie/fermeture/protection solaire (tout matériau)/serrurerie/coffre-fort",
         "Matériel de sécurité pour le bâtiment",
         "Domotique/immotique",
         "Ingénierie de la construction (architecture, géomètrie,...)",
         AUTRE,
         "Terrassement/fondation",
         "Ouvrage d’art (tunnel, pont, port, aérodrome)",
         "Adduction d’eau/assainissement (égoût)",
         "Travaux routiers (trottoir, route, autoroute, carrefour)",
         "Voie ferrée",
         AUTRE,
         "Systèmes de production de chaleur",
         "Systèmes de production de froid",
         "Climatisation / Ventilation",
         "Équipements pour le secteur thermique",
         "Services pour le secteur thermique",
         AUTRE,
         "Production d'électricité renouvelable (éolien, solaire, hydraulique, énergies marines)",
         "Autres productions d’électricité (nucléaire, gaz, fuel, charbon)",
         "Cogénération",
         "Biocarburants",
         "Biocombustibles (bois, biogaz, gaz de synthèse,...)",
         "Hydrogène / pile à combustible",
         "Géothermie",
         "Exploration / production d'hydrocarbures",
         "Transport / distribution d'hydrocarbures",
         "Stockage de l’énergie",
         "Captage / stockage de CO2",
         "Transport / distribution d'électricité",
         "Systèmes / équipements de contrôle pour l’énergie",
         "Services pour le secteur de l'énergie",
         AUTRE,
         "Ascenseur",
         "Escalier mécanique",
         "Téléphérique",
         "Levage (grue, pont-levage,...)",
         "Manutention (chargement/déchargement,...)",
         "Convoyage",
         "Stockage",
         "Équipements pour le secteur manutention",
         "Services pour le secteur de la manutention",
         AUTRE,
         "Moteurs (sauf transport), turbines (sauf énergie)",
         "Pompes, compresseurs",
         "Transmission oléo-hydraulique/mécanique",
         "Organes mécaniques de transmission",
         "Roulement, engrenage",
         "Robinetterie",
         "Bijouterie/horlogerie",
         "Machines-outils portatives",
         "Machines-outils autres (non destinées à un secteur particulier)",
         "Machines-outils UGV",
         "Machines spéciales (non destinées à un secteur particulier)",
         "Gestion de chaîne de production/parc de machines (intégration de TIC, supervision, télémaintenance,...)",
         "Outils/systèmes de contrôle pour le secteur mécanique",
         AUTRE,
         "Communications fixes et nomades (filaires et sans fil/hertziens)",
         "Communications mobiles",
         "Communications satellitaires",
         "Terminaux et plates-formes pour services mobiles",
         "Service de télécommunication fixe et mobile",
         "Infrastructures/réseaux haut débit et bas débit",
         "Services de communications",
         "Gestion et sécurité des services et réseaux",
         "Test et validation des services, des équipements et des réseaux",
         AUTRE,
         "Ordinateur/périphérique",
         "Serveur",
         "Machines de bureau",
         "Reprographie",
         "Enregistrement informatique",
         "Autres matériels informatiques",
         AUTRE,
         "Ingénierie, outils de développement",
         "Informatique de gestion et Management des systèmes d'information",
         "Informatique Industrielle, Scientifique et Technique",
         "Internet (traitement et hébergement de données, portails internet, moteur de recherche, services d'information et d'intermédiation, eCommerce...)",
         AUTRE,
         "Édition de jeux électroniques : jeu vidéo, contenus ludo-éducatifs (serious game) (jeux en ligne, logiciels de jeu, jeu en téléchargement)",
         "Production post-production, effets spéciaux, images de synthèse, relief pour l'audiovisuel : cinéma, films d'animation, télévision, films institutionnels et publicitaires, vidéo",
         "Production post-production, effets spéciaux pour l'édition musicale, son et radio",
         "Services de contenus audiovisuels (TV, radio, VOD, TVIP, portails Internet audiovisuels)",
         "Sécurité des contenus audiovisuels et des accès",
         "Instruments de musique",
         "Matériel photo cinéma/optique",
         AUTRE,
         "Finance/assurance/comptabilité/gestion",
         "Immobilier",
         "Tourisme/hébergement/voyage",
         "Loisir/culture/sports",
         "Collectivités locales/administration publique, e-administration",
         "Activités juridiques",
         "Commerce, gros, détail, e-commerce, intermédiation",
         "Édition (presse, livres, jeux de société)",
         "Publicité/marketing/information consommateur, étude de marché",
         "Ressources humaines/formation/enseignement/management",
         "Services à la personne (hors E-santé)",
         AUTRE,
         "Chimie fine",
         "Chimie du solide (cristallographie, fibres cristallines, solides divisés)",
         "Colorants, pigments et agents tannants",
         "Produits chimiques organiques",
         "Produits chimiques inorganiques",
         "Produits biosourcés (formulation chimique )",
         "Équipements pour le secteur chimie",
         "Services pour le secteur de la chimie",
         AUTRE,
         "Peinture et vernis",
         "Explosifs/Pyrotechnie",
         "Encres",
         "Savons, détergents et produits d’entretien",
         "Parfums et produits de toilette (sauf produits cosmétiques)",
         "Colles, adhésifs",
         "Lubrifiant, graisse, huiles ou cires",
         "Produits chimiques à usage industriel  (solvant, abrasif,...)",
         "Huiles essentielles",
         "Biocide (formulation chimique)",
         "Équipements pour le secteur parachimie",
         "Services pour le secteur parachimie",
         AUTRE,
         "Production d'intermédiaires chimiques (synthons)",
         "Production de molécules complexes (acides, alcools, monomères, oligomères,...)",
         "Biocide (formulation renouvelable)",
         AUTRE,
         "Molécules issues de matières premières renouvelables (agro-ressources, polysaccharides et dérivés,...)   pour production chimique",
         "Amélioration de souches pour production chimique",
         "Fermentation par levure pour production chimique",
         "Fermentation par autres microorganismes ( cellules animales, végétales, algues,...) pour production chimique",
         "Biocatalyse",
         "Coproduits issus des bioraffineries",
         AUTRE,
         "Air/effluents atmosphériques",
         "Déchets industriels",
         "Déchets ménagers",
         "Déchets agricoles",
         "Déchets médicaux",
         "Eau/effluents aqueux",
         "Boues",
         "Bruit/nuisance sonore",
         "Sol/sous-sol",
         "Risques industriels",
         "Risques naturels",
         "Risques sanitaires",
         "Météorologie",
         "Milieu naturel/faune/flore",
         "Propreté et entretien urbain",
         "Outils de mesure/contrôle/analyse pour l’environnement",
         "Ingénierie pour le secteur environnement",
         AUTRE,
         "Alarme",
         "Antivol",
         "Incendie",
         "Contrôle d’accès (biométrie, badges,...)",
         "Systèmes de surveillance",
         "Autres systèmes de sécurité des personnes et des biens",
         "Systèmes de sécurisation/authentification (passeport, contrefaçon,...)",
         "Services pour le secteur sécurité",
         AUTRE,
         "Appareils de mesure et d’analyse",
         "Appareils de contrôle de process",
         "Capteur intégré",
         "Contrôle non destructif",
         "Métrologie",
         "Instrumentation scientifique (appareil de laboratoire)",
         "Équipements pour le secteur mesure-contrôle",
         AUTRE,
         "Construction aéronautique et spatial",
         "Construction d'équipements de transport aérien",
         "Matériel aéroportuaire",
         "Organisation et ingénierie du transport aérien (service)",
         AUTRE,
         "Construction de véhicules de transport routier (automobile, poids lourd, bus, motos, cycles)",
         "Construction d'équipements automobiles et autres matériels roulant",
         "Infrastructures de transport routier",
         "Organisation et ingénierie du transport routier (service)", AUTRE,
         "Construction d'équipements et de matériel ferroviaire roulant",
         "Construction ferroviaire",
         "Organisation et ingénierie du transport ferroviaire (service)",
         "Systèmes de systèmes", AUTRE,
         "Construction navale et structure flottante",
         "Organisation et ingénierie du transport ferroviaire (service)",
         "Plaisance", AUTRE };

   public static final String[] EQUIPEMENTS = {
         "Plateforme géomatique pour l'intelligence de la donnée spatiale - INTELESPACE",
         COMMENTAIRE,
         "Microsystèmes Capteurs Chimiques - MS2C",
         COMMENTAIRE,
         "Essais en compatibilité électromagnétique -PACEM",
         COMMENTAIRE,
         "Spectroscopies optiques",
         COMMENTAIRE,
         "Grille régionale de calcul - AuverGrid",
         COMMENTAIRE,
         "Développement technologiques génies fermentaire et alimentaire - BIO-UP",
         COMMENTAIRE,
         "Centre Investigation Clinique - CIC",
         COMMENTAIRE,
         "Criblage à haut débit",
         COMMENTAIRE,
         "Diffraction des rayons X",
         COMMENTAIRE,
         "Spectroscopies électroniques - ESCA",
         COMMENTAIRE,
         "Plateforme sur la transgénèse - Fly Facility",
         COMMENTAIRE,
         "Plateforme filière Forêt Bois - Forbois",
         COMMENTAIRE,
         "Séquençage haut débit - GINA",
         COMMENTAIRE,
         "Plateforme de spectrométrie des analyses chimiques d'élements majeurs, traces et isotopes par torches à plasma - ICP-AES et ICP-MS",
         COMMENTAIRE,
         "Modélisation et Technologies de l’Information",
         COMMENTAIRE,
         "Mastication artificielle",
         COMMENTAIRE,
         "Plateforme des études de métabolomique - Metabolic Profiler",
         COMMENTAIRE,
         "Microscopie électronique analytique à transmission des matériaux solides",
         COMMENTAIRE,
         "Microscopie optique et électronique des échantillons biologiques",
         COMMENTAIRE,
         "Microsonde - MEB",
         COMMENTAIRE,
         "Véhicules Intelligents - PAVIN",
         COMMENTAIRE,
         "Plateforme des irradiations de matériel biologique et non biologique - PAVIRMA",
         COMMENTAIRE, "Plasma et Matériaux - PLASMAT", COMMENTAIRE,
         "Résonance Magnétique Nucléaire - RMN", COMMENTAIRE,
         "Résonance Paramagnétique Electronique - RPE", COMMENTAIRE,
         "Spectroscopies vibrationnelles", COMMENTAIRE,
         "Spectrométrie de masse", COMMENTAIRE,
         "Plate-forme d’imagerie multimodalité", COMMENTAIRE, "Autre :",
         COMMENTAIRE, };
   public static final String NATHALIE = "Nathalie";
   public static final String DOMINIQUE = "Dominique";
   public static final String PASCAL = "Pascal";
   public static final String PHILIPPE = "Philippe";
   public static final String[][] CONTACTEXPERT = {
         { "Mme", "Hecquet", "Laurence",
               "Laurence.HECQUET@univ-bpclermont.fr", "04 73 40 78 71" },
         { "Mr", "Sarakha", "Mohamed", "Mohamed.SARAKHA@univ-bpclermont.fr",
               "04 73 40 71 70" },
         { "Mr", "Leroux", "Fabrice", "Fabrice.LEROUX@univ-bpclermont.fr",
               "04 73 40 70 36" },
         { "Mr", "Padua", "Agilio", "Agilio.PADUA@univ-bpclermont.fr",
               "04 73 40 71 66" },
         { "Mme", "Ducki", "Sylvie", "Sylvie.DUCKI@ensccf.fr",
               "04 73 40 77 17" },
         { "Mme", "Sellegri", "Karine",
               "K.Sellegri@opgc.univ-bpclermont.fr", "04 73 40 73 94" },
         { "Mr", "Van Baelen", "Joël", "Joel.VAN_BAELEN@univ-bpclermont.fr",
               "04 73 40 51 36" },
         { "Mr", "Schwarzenboeck", "Alfons",
               "Alfons.SCHWARZENBOECK@univ-bpclermont.fr",
               "04 73 40 51 36" },
         { "Mr", "Guillin", "Arnaud", "Arnaud.GUILLIN@univ-bpclermont.fr",
               "04 73 40 70 90" },
         { "Mr", "Touzani", "Rachid", "Rachid.TOUZANI@univ-bpclermont.fr",
               "04 73 40 77 06" },
         { "Mr", "Bichon", "Julien", "Julien.BICHON@univ-bpclermont.fr",
               "04 73 40 70 75" },
         { "Mr", "Royer", "Emmanuel", "Emmanuel.ROYER@univ-bpclermont.fr",
               "04 73 40 78 91" },
         { "Mr", "PARIS", "Raphaël", "Raphael.PARIS@univ-bpclermont.fr",
               "04 73 34 67 17" },
         { "Mme", "Bolfan-Casanova", NATHALIE,
               "N.Bolfan@opgc.univ-bpclermont.fr", "04 73 34 67 42" },
         { "Mme", "Boyet", "Maud", "M.Boyet@opgc.univ-bpclermont.fr",
               "04 73 34 67 35" },
         { "Mme", "Celle-Jeanton", "Hélène",
               "h.Celle-Jeanton@opgc.univ-bpclermont.fr", "04 73 34 67 54" },
         { "Mme", "Koga", "Estelle", "E.Koga@opgc.univ-bpclermont.fr",
               "04 73 34 67 61" },
         { "Mr", "Bouhifd", "Ali", "A.Bouhifd@opgc.univ-bpclermont.fr",
               "04 73 34 67 72" },
         { null, null, null, null, null },
         { "Mr", "Pallin", DOMINIQUE, "Dominique.PALLIN@clermont.in2p3.fr",
               "04 73 26 45 98" },
         { "Mr", "Perret", PASCAL, "Pascal.PERRET@clermont.in2p3.fr",
               "04 73 26 45 98" },
         { "Mr", "Gris", PHILIPPE, "Philippe.GRIS@clermont.in2p3.fr",
               "04 73 40 77 93" },
         { "Mr", "Gay", PASCAL, "Pascal.GAY@clermont.in2p3.fr",
               "04 73 26 45 97" },
         { "Mme", "Carloganu", "Cristina",
               "Cristina.CARLOGANU@clermont.in2p3.fr", "04 73 40 72 92" },
         { "Mr", "Dupieux", PASCAL, "Pascal.DUPIEUX@clermont.in2p3.fr",
               "04 73 26 45 99" },
         { "Mr", "Roche", "Guy", "guy.roche@in2p3.fr", EMPTY },
         { "Mr", "Bastid", "Nicole", "Nicole.BASTID@clermont.in2p3.fr",
               "04 73 40 73 15" },
         { "Mme", "C.", "Hyde", EMPTY, EMPTY },
         { "Mr", "Mathiot", "Jean-François",
               "Jean-Francois.MATHIOT@univ-bpclermont.fr",
               "04 73 40 70 34" },
         { "Mr", "Montarou", "Gérard", "Gerard.MONTAROU@clermont.in2p3.fr",
               "04 73 40 79 86" },
         { "Mme", "Maigne", "Lydia", "Lydia.MAIGNE@clermont.in2p3.fr",
               "04 70 02 20 27" },
         { "Mr", "Jallot", "Edouard", "Edouard.JALLOT@univ-bpclermont.fr",
               "04 73 40 72 65" },
         { "Mr", "Miallier", "Didier", "Didier.MIALLIER@clermont.in2p3.fr",
               "04 73 40 51 24" },
         { null, null, null, null, null },
         { "Mme", "Boisseau", NATHALIE,
               "Nathalie.BOISSEAU@univ-bpclermont.fr", "04 73 40 55 19" },
         { "Mr", "Ratel", "Sébastien", "Sebastien.RATEL@univ-bpclermont.fr",
               "04 73 40 55 02" },
         { null, null, null, null, null },
         { "Mr", "Paux", "Etienne", "etienne.paux@clermont.inra.fr",
               "04 73 62 43 86" },
         { "Mr", "Salse", "Jérôme", "Jerome.SALSE@univ-bpclermont.fr",
               "04 73 62 43 80" },
         { "Mr", "Le gouis", "Jacques",
               "Jacques.LE_GOUIS@univ-bpclermont.fr", EMPTY },
         { "Mme", "Ravel", "Catherine", "ravel@clermont.inra.fr",
               "04 73 62 43 10" },
         { "Mr", "Langin", "Thierry", "Thierry.LANGIN@univ-bpclermont.fr",
               "04 73 62 44 47" },
         { "Mr", "Charmet", "Gilles", "Gilles.CHARMET@univ-bpclermont.fr",
               "04 73 62 43 09" },
         { null, null, null, null, null },
         { "Mr", "Mathieu", "Olivier", "Olivier.MATHIEU@univ-bpclermont.fr",
               "04 73 40 74 07" },
         { "Mr", "Probst", "Aline", "Aline.PROBST@univ-bpclermont.fr",
               "04 73 40 53 04" },
         { "Mr", "Vaury", "Chantal", "chantal.vaury@udamail.fr",
               "04 73 17 81 84" },
         { "Mr", "White", "Charles", "Charles.WHITE@univ-bpclermont.fr",
               "04 73 40 77 52" },
         { "Mr", "Chazaud", "Claire", "Claire.CHAZAUD@univ-bpclermont.fr",
               "04 73 17 83 80" },
         { "Mr", "Drevet", "Joël", "Joel.DREVET@univ-bpclermont.fr",
               "04 73 40 74 13" },
         { "Mr", "Jagla", "Krzystof", "christophe.jagla@udamail.fr",
               "04 73 17 81 81" },
         { "Mr", "Mirouse", "Vincent", "vincent.mirouse@udamail.fr",
               "04 73 17 81 71" },
         { "Mr", "Lobaccaro", "Jean-Marc",
               "J-Marc.LOBACCARO@univ-bpclermont.fr", "04 73 40 74 16" },
         { "Mr", "Martinez", "Antoine",
               "Antoine.MARTINEZ@univ-bpclermont.fr", "04 73 40 74 09" },
         { null, null, null, null, null },
         { "Mr", "Delbac", "Frédéric", "Frederic.DELBAC@univ-bpclermont.fr",
               "04 73 40 78 68" },
         { "Mr", "Forestier", "Christiane",
               "christiane.forestier@udamail.fr", "04 73 17 79 94" },
         { "Mr", "Debroas", "Dider", "Didier.DEBROAS@univ-bpclermont.fr",
               "04 73 40 78 37" },
         { "Mr", "SIME-NGANDO", "Telesphore",
               "Telesphore.SIME-NGANDO@univ-bpclermont.fr",
               "04 73 40 78 36" },
         { "Mr", "Desvilette", "Christian",
               "Christian.DESVILETTES@lbp.univ-bpclermont.fr",
               "04 73 40 76 71" },
         { null, null, null, null, null },
         { "Mr", "Cochard", "Hervé", "Herve.Cochard@clermont.inra.fr",
               "04 73 62 44 71" },
         { "Mr", "Moulia", "Bruno", "Bruno.MOULIA@univ-bpclermont.fr",
               "04 73 62 44 74" },
         { "Mr", "Lacointe", "André", "Andre.Lacointe@clermont.inra.fr",
               "04 73 62 43 67" },
         { null, null, null, null, null },
         { "Mr", "Vernet", "Patrick", "Patrick.VERNET@univ-bpclermont.fr",
               "04 73 40 74 00" },
         { "Mr", "Vernet", "Patrick", "Patrick.VERNET@univ-bpclermont.fr",
               "04 73 40 74 00" },
         { null, null, null, null, null },
         { "Mr", "Derutin", "Jean-Pierre",
               "J-Pierre.DERUTIN@lasmea.univ-bpclermont.fr",
               "04 73 40 72 63" },
         { "Mr", "Malpuech", "Guillaume",
               "Guillaume.MALPUECH@lasmea.univ-bpclermont.fr",
               "04 73 40 52 58" },
         { "Mr", "Chateauneuf", "Alaa",
               "alaa.chateauneuf@univ-bpclermont.fr", "04 73 40 75 25" },
         { "Mr", "Dussap", "Claude-Gilles",
               "C-Gilles.DUSSAP@univ-bpclermont.fr", "04 73 40 78 38" },
         { null, null, null, null, null },
         { "Mr", "Baiou", "Mourad", "Mourad.Baiou@isima.fr",
               "04 73 40 55 01" },
         { "Mr", "Misson", "Michel", "Michel.Misson@isima.fr", EMPTY },
         { "Mr", "Gourgand", "Michel", "Michel.Gourgand@isima.fr",
               "04 73 40 75 14" },
         { "Mr", "Xie", "Xiao-Lan", "Xiaolan.XIE@univ-bpclermont.fr", EMPTY },
         { null, null, null, null, null },
         { "Mr", "André", PASCAL, "Pascal.ANDRE@univ-bpclermont.fr",
               "04 73 40 77 39" },
         { "Mr", "Faure", "Géraldine", "Geraldine.FAURE@univ-bpclermont.fr",
               "04 73 40 73 22" },
         { "Mr", "Abbaaoui", "M’hammed",
               "M-Hammed.ABBAOUI@univ-bpclermont.fr", "04 73 40 73 25" },
         { "Mr", "Rochette", "David", "David.ROCHETTE@univ-bpclermont.fr",
               "04 70 02 20 16" },
         { "Mr", "Bussière", "William",
               "William.BUSSIERE@univ-bpclermont.fr", "04 73 40 77 04" },
         { null, null, null, null, null },
         { "Mr", "Cizeron", "Marc", "Marc.CIZERON@univ-bpclermont.fr",
               "04 73 40 76 91" },
         { "Mr", "Rix-lièvre", "Géraldine",
               "Geraldine.RIX@univ-bpclermont.fr", "04 73 40 78 55" },
         { "Mr", "Coutarel", "Fabien", "Fabien.COUTAREL@univ-bpclermont.fr",
               "04 73 40 77 35" },
         { "Mme", "Petitfaux", NATHALIE,
               "nathalie.gal-petitfaux@univ-bpclermont.fr",
               "04 73 40 75 40" },
         { null, null, null, null, null },
         { "Mr", "Poignault", "Rémy", "Remy.POIGNAULT@univ-bpclermont.fr",
               "04 73 34 66 22" },
         { "Mr", "Antoine", PHILIPPE, "Philippe.ANTOINE@univ-bpclermont.fr",
               "04 73 34 65 27" },
         { "Mr", "Neiva", "Saulo", "Saulo.NEIVA@univ-bpclermont.fr",
               "04 73 40 63 77" },
         { "Mr", "Coyault", "Sylviane",
               "Sylviane.COYAULT@univ-bpclermont.fr", "04 73 34 68 61" },
         { null, null, null, null, null },
         { "Mme", "Fournier", "Mauricette",
               "Mauricette.FOURNIER@univ-bpclermont.fr", "04 73 34 66 36" },
         { "Mme", "Roth", "Hélène", "Helene.ROTH@univ-bpclermont.fr",
               "04 73 34 66 52" },
         { null, null, null, null, null },
         { "Mr", "Descotes", DOMINIQUE,
               "Dominique.DESCOTES@univ-bpclermont.fr", "04 73 34 68 30" },
         { "Mr", "Descotes", DOMINIQUE,
               "Dominique.DESCOTES@univ-bpclermont.fr", "04 73 34 68 30" },
         { "Mme", "Bertrand", DOMINIQUE,
               "Dominique.BERTRAND@univ-bpclermont.fr", "04 73 34 68 27" },
         { null, null, null, null, null },
         { "Mr", "Caron", "Jean-Claude",
               "J-Claude.CARON@univ-bpclermont.fr", "04 73 34 66 12" },
         { "Mr", "Bourdin", PHILIPPE, "Philippe.BOURDIN@univ-bpclermont.fr",
               "04 73 34 65 78" },
         { "Mr", "Fray", "Jean-Luc", "J-Luc.FRAY@univ-bpclermont.fr",
               "04 73 34 65 77" },
         { "Mr", "Luis", "Jean-Philippe",
               "J-Philippe.LUIS@univ-bpclermont.fr", "04 73 34 65 93" },
         { null, null, null, null, null },
         { "Mr", "Miras", "Yannick", "Yannick.MIRAS@univ-bpclermont.fr",
               "04 73 34 68 21" },
         { "Mr", "Steiger", "Johannes",
               "Johannes.STEIGER@univ-bpclermont.fr", "04 73 34 68 43" },
         { "Mr", "Rouvellac", "Eric", "Eric.ROUVELLAC@univ-bpclermont.fr",
               "05 55 43 56 00" },
         { null, null, null, null, null },
         { "Mme", "Darnon", "Céline", "Celine.DARNON@univ-bpclermont.fr",
               "04 73 40 85 17" },
         { "Mme", "Guimond", "Serge", "Serge.GUIMOND@univ-bpclermont.fr",
               "04 73 40 85 16" },
         { "Mme", "Droit-Volet", "Sylvie",
               "Sylvie.DROIT-VOLET@univ-bpclermont.fr", "04 73 40 85 07" },
         { "Mr", "Ferrand", "Ludovic", "Ludovic.FERRAND@univ-bpclermont.fr",
               "04 73 40 62 57" },
         { null, null, null, null, null },
         { "Mme", "Bodelot", "Colette",
               "Colette.BODELOT@univ-bpclermont.fr", "04 73 34 65 33" },
         { "Mr", "Chabanal", "Damien", "Damien.CHABANAL@univ-bpclermont.fr",
               "04 73 34 65 60" },
         { "Mr", "Spitzl-Dupic", "Friederike",
               "Friederike.SPITZL-DUPIC@univ-bpclermont.fr",
               "04 73 40 63 43" },
         { "Mme", "Foucher", "Anne-Laure",
               "A-Laure.FOUCHER@univ-bpclermont.fr", "04 73 34 65 62" },
         { null, null, null, null, null },
         { "Mr", "Gandon", "Sébastien",
               "Sebastien.GANDON@univ-bpclermont.fr", "04 73 34 68 54" },
         { "Mr", "Cattin", "Emmanuel", "Emmanuel.CATTIN@univ-bpclermont.fr",
               "04 73 34 66 75" },
         { "Mr", "Petit", "Alain", "Alain.PETIT@univ-bpclermont.fr",
               "04 73 34 66 47" }, { null, null, null, null, null },
         CELINE, CELINE, CELINE, CELINE, { null, null, null, null, null } };
   public static final String[] URL = { ICCF, ICCF, ICCF, ICCF, ICCF, LAMP,
         LAMP, LAMP, LM, LM, LM, LM, LMV, LMV, LMV, LMV, LMV, LMV, null,
         LPC, LPC, LPC, LPC, LPC, LPC, LPC, LPC, LPC, LPC, LPC, LPC, LPC,
         LPC, null, AME2P, AME2P, null, GDEC, GDEC, GDEC, GDEC, GDEC, GDEC,
         null, GRED, GRED, GRED, GRED, GRED, GRED, GRED, GRED, GRED, GRED,
         null, LMGE, LMGE, LMGE, LMGE, LMGE, null, PIAF, PIAF, PIAF, null,
         RGM, RGM, null, IP, IP, IP, IP, null, LIMOS, LIMOS, LIMOS, LIMOS,
         null, LAEPT, LAEPT, LAEPT, LAEPT, LAEPT, null, ACTE, ACTE, ACTE,
         ACTE, null, CELIS, CELIS, CELIS, CELIS, null, CERAMAC, CERAMAC,
         null, CERHAC, CERHAC, CERHAC, null, CHEC, CHEC, CHEC, CHEC, null,
         GEOLAB, GEOLAB, GEOLAB, null, LAPSCO, LAPSCO, LAPSCO, LAPSCO, null,
         LRL, LRL, LRL, LRL, null, PHIER, PHIER, PHIER, null, CRCGM, CRCGM,
         CRCGM, CRCGM, null };
   public static final String[] LABO = {
         "Institut de Chimie de Clermont-Ferrand ICCF, UMR 6296",
         "Laboratoire de Météorologie Physique LaMP, UMR 6016",
         "Laboratoire de Mathématiques LM, UMR 6620",
         "Laboratoire Magmas et Volcans LMV, UMR 6524",
         "Laboratoire de Physique Corpusculaire LPC, UMR 6533",
         "Institut Pascal IP, UMR 6602",
         "Laboratoire Arc Electrique et Plasmas Thermiques LAEPT, EA 4646",
         "Laboratoire d’Informatique, de Modélisation et d’Optimisation des Systèmes LIMOS, UMR 6158",
         "Laboratoire des Adaptations Métaboliques à l’Exercice en conditions Physiologiques et Pathologiques AME2P, EA 3533",
         "Laboratoire Génétique, Diversité et Écophysiologie des Céréales GDEC, UMR A 1095",
         "Laboratoire Génétique, Reproduction et Développement GReD, UMR CNRS 6293, INSERM U1103",
         "Laboratoire Microorganismes : Génome et Environnement LMGE, UMR 6023",
         "Laboratoire de Physique et Physiologie Intégratives de l’Arbre Fruitier et Forestier PIAF, UMR A 547",
         "Réparation du Génome Mitochondrial Normal et Pathologique RGM, EA 4645",
         "Laboratoire Activité - Connaissance - Transmission - éducation ACTé, EA 4281",
         "Centre de Recherches sur les Littératures et la Sociopoétique CELIS, EA 1002",
         "Centre d’Etudes et de Recherches Appliquées au Massif Central, à la moyenne montagne et aux espaces fragiles CERAMAC, EA 997",
         "Institut d’Histoire de la Pensée Classique - Équipe Centre d’Études sur les Réformes, l’Humanisme et l’Âge Classique IHPC/CERHAC - UMR 5037",
         "Centre d’Histoire « Espaces et Cultures » CHEC, EA 1001",
         "Laboratoire Communication et solidarité EA 4647",
         "Espaces Humains et Interactions Culturelles EHIC, EA 1087",
         "Laboratoire de Géographie Physique et Environnementale GEOLAB, UMR 6042",
         "Laboratoire de Psychologie Sociale et Cognitive LAPSCO, UMR 6024",
         "Laboratoire de Recherche sur le Langage LRL, EA 999",
         "Laboratoire Philosophies et Rationalités PHIER, EA 3297",
         "Centre de Recherche Clermontois en Gestion et Management CRCGM, EA 3849",
         "Maison des Sciences de l'Homme+PUBP, MSH, USR 3550",
         "Observatoire de Physique du Globe, OPGC, UMS 833" };

   public static final String LAMPID = "21652";
   public static final String LMVID = "21642";
   public static final String LPCID = "50338";
   public static final String AME2PID = "39401";
   public static final String GDECID = "50340";
   public static final String GREDID = "50344";
   public static final String LMGEID = "21649";
   public static final String PIAFID = "28959";
   public static final String LIMOSID = "21646";
   public static final String LAEPTID = "20643";
   public static final String CHECID = "50342";
   public static final String LAPSCOID = "39532";
   public static final String[] ENTITYID = {
         "21641",
         "21645",
         "21401",
         "39382",
         LAMPID,
         LAMPID,
         LPCID,
         EMPTY,// LM
         EMPTY, EMPTY, EMPTY, null, LMVID, LMVID, LMVID, LMVID, LMVID,
         LMVID, null, LPCID, LPCID, LPCID, LPCID, LPCID, LPCID, LPCID,
         LPCID, LPCID, LPCID, LPCID, LPCID, LPCID, LPCID, null, AME2PID,
         AME2PID, null, GDECID, GDECID, GDECID, GDECID, GDECID, GDECID,
         null, GREDID, GREDID, GREDID, GREDID, GREDID, GREDID, GREDID,
         GREDID, GREDID, GREDID, null, LMGEID, LMGEID, LMGEID, LMGEID,
         LMGEID, null, PIAFID, PIAFID, PIAFID,
         null,
         EMPTY,// RGM
         EMPTY,
         null,
         EMPTY,// ISPR
         EMPTY,// PHOTON
         "21653", "39395", null, LIMOSID, LIMOSID, LIMOSID, LIMOSID, null,
         LAEPTID, LAEPTID, LAEPTID, LAEPTID, LAEPTID, null,
         EMPTY,// ACTé
         EMPTY, EMPTY, EMPTY, null,
         EMPTY,// CELIS
         EMPTY, EMPTY, EMPTY, null,
         EMPTY,// CERAMAC
         EMPTY, null,
         EMPTY,// IHPC/CERHAC
         EMPTY, EMPTY, null, CHECID, CHECID, CHECID, CHECID, null,
         EMPTY,// GEOLAB
         EMPTY, EMPTY, null, LAPSCOID, LAPSCOID, LAPSCOID, LAPSCOID, null,
         EMPTY,// LRL
         EMPTY, EMPTY, EMPTY, null, EMPTY,// PHIER
         EMPTY, EMPTY, null, EMPTY,// CRCGM
         EMPTY, EMPTY, EMPTY, null };

   public static final String[] TITLE = { "Titre de la compétence", "Entite",
         "Savoir-faire", "Domaine", "Sous-domaine", "mots-clés", "Secteur",
         "Sous-secteur", "Equipements",
         "Applications et exemple de réalisations", "Type de prestation",
         "Civilité-contact expert", "Firstname-contact expert",
         "Surname-contact expert", "Email-contact expert",
         "Tel-contact expert", "URL", "Certification/Label/Agrément",
         "Institut Carnot ou IRT ou IEED ou SRC", "Brevets" };

   private Config() {
   }
}